#!/bin/bash

trap 'echo "error_lock" > /error_lock; exit 1' ERR
if [ -f "/error_lock" ]; then
    echo "start failed, please check the log"
    sleep 30
    exit 1
fi

echo "Current shell: $SHELL"
echo "Running in $(bash --version)"

echo "---------------------------------------------------------------------------------"
cat "$0"

echo "---------------------------------------------------------------------------------"
printenv

ESD_FILE_VERSION='1.5.0'
export BUCKET_NAME="aws-gcr-solutions-$AWS_DEFAULT_REGION"

echo "---------------------------------------------------------------------------------"
echo "INSTANCE_TYPE: $INSTANCE_TYPE"
echo "INSTANCE_PACKAGE: $INSTANCE_PACKAGE"
echo "ENDPOINT_NAME: $ENDPOINT_NAME"
echo "ENDPOINT_ID: $ENDPOINT_ID"
echo "ESD_FILE_VERSION: $ESD_FILE_VERSION"
echo "CREATED_AT: $CREATED_AT"
created_time_seconds=$(date -d "$CREATED_AT" +%s)
current_time=$(date "+%Y-%m-%dT%H:%M:%S.%6N")
current_time_seconds=$(date -d "$current_time" +%s)
init_seconds=$(( current_time_seconds - created_time_seconds ))
echo "NOW_AT: $current_time"
echo "Init from Create: $init_seconds seconds"

echo "---------------------------------------------------------------------------------"

total_start_at=$(date +%s)
start_at=$(date +%s)
s5cmd --log=error cp "s3://$BUCKET_NAME/esd/$ESD_FILE_VERSION-$INSTANCE_PACKAGE/commands.txt" ./
s5cmd --log=error run commands.txt
end_at=$(date +%s)
cost=$((end_at-start_at))
echo "download files: $cost seconds"

start_at=$(date +%s)
tar -xf webui.tar
pwd
ls -la
end_at=$(date +%s)
cost=$((end_at-start_at))
echo "decompress files: $cost seconds"

end_at=$(date +%s)
cost=$((end_at-total_start_at))
echo "files total cost: $cost seconds"

echo "---------------------------------------------------------------------------------"
total_cost=$((cost+init_seconds))
echo "total cost: $total_cost seconds"

# if $EXTENSIONS is not empty, it will be executed
if [ -n "$EXTENSIONS" ]; then
    echo "---------------------------------------------------------------------------------"
    cd /home/ubuntu/stable-diffusion-webui/extensions/ || exit 1

    read -ra array <<< "$(echo "$EXTENSIONS" | tr "," " ")"

    for git_repo in "${array[@]}"; do
      start_at=$(date +%s)
      echo "git clone $git_repo"
      git clone "$git_repo"
      end_at=$(date +%s)
      cost=$((end_at-start_at))
      echo "git clone $git_repo: $cost seconds"
    done
fi

cd /home/ubuntu/stable-diffusion-webui || exit 1

# s5cmd
mkdir tools
cp /usr/local/bin/s5cmd ./tools/

source /home/ubuntu/stable-diffusion-webui/venv/bin/activate

echo "---------------------------------------------------------------------------------"
echo "accelerate launch..."

accelerate launch --num_cpu_threads_per_process=6 launch.py --api --listen --port 8080 --xformers --no-half-vae --skip-prepare-environment --no-download-sd-model --skip-python-version-check --skip-install --skip-version-check --no-hashing --nowebui
