#!/bin/bash
echo "Current shell: $SHELL"
trap 'echo "error_lock" > error_lock; exit 1' ERR

mkdir -p ~/.aws
echo "[default]
region = $AWS_DEFAULT_REGION" > ~/.aws/config

nvidia-smi

ESD_FILE_VERSION='1.8.0-base'

echo "---------------------------------------------------------------------------------"
echo "INSTANCE_TYPE: $INSTANCE_TYPE"
echo "ENDPOINT_NAME: $ENDPOINT_NAME"
echo "ENDPOINT_ID: $ENDPOINT_ID"
echo "ESD_FILE_VERSION: $ESD_FILE_VERSION"
echo "EXTENSIONS: $EXTENSIONS"
echo "CREATED_AT: $CREATED_AT"
echo "Now At: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"

echo "---------------------------------------------------------------------------------"
instance_package="g5"
if [ "${INSTANCE_TYPE%"${INSTANCE_TYPE#ml.g4}"}" = "ml.g4" ]; then
    instance_package="g4"
fi

echo "instance_package: $instance_package"

export INSTALL_SCRIPT=https://raw.githubusercontent.com/awslabs/stable-diffusion-aws-extension/dev/install.sh
export START_FAST=0

cd /home/ubuntu
if [ ! -d "stable-diffusion-webui" ]; then
  curl -sSL "$INSTALL_SCRIPT" | bash;
#  export START_FAST=0
fi

cd stable-diffusion-webui
if [ ! -d "venv" ];then
  python3 -m venv venv;
fi

chmod +x /home/ubuntu/stable-diffusion-webui/venv/bin/*

source venv/bin/activate
python -m pip install --upgrade pip
python -m pip install accelerate
python -m pip install markdown

if [ $START_FAST -eq 1 ]; then
  accelerate launch --num_cpu_threads_per_process=6 launch.py --api --listen --port 8080 --xformers --no-half-vae --skip-prepare-environment --no-download-sd-model --skip-python-version-check --skip-install --skip-version-check --no-hashing --nowebui --skip-torch-cuda-test
fi

accelerate launch --num_cpu_threads_per_process=6 launch.py --api --listen --port 8080 --xformers --no-half-vae --no-download-sd-model --no-hashing --nowebui --skip-torch-cuda-test

# s5cmd
#cd /home/ubuntu
#tar -cvf stable-diffusion-webui.tar ./stable-diffusion-webui
#s5cmd cp stable-diffusion-webui.tar s3://elonniu/1.8.0-base-g5/stable-diffusion-webui2.tar
