#!/bin/bash
echo "Current shell: $SHELL"
echo "Running in $(bash --version)"
trap 'echo "error_lock" > error_lock; exit 1' ERR

if [ -f "error_lock" ]; then
    echo "init failed, please check the log"
    sleep 10
    exit 1
fi

echo "---------------------------------------------------------------------------------"
cat compress

echo "---------------------------------------------------------------------------------"
printenv
AWS_DEFAULT_REGION="us-east-1"
mkdir -p ~/.aws
echo "[default]
region = $AWS_DEFAULT_REGION" > ~/.aws/config
echo "---------------------------------------------------------------------------------"
echo "ESD_FILE_VERSION: $ESD_FILE_VERSION"
echo "EXTENSIONS: $EXTENSIONS"
echo "Now At: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"

ESD_FILE_VERSION='1.8.0-base'

echo "---------------------------------------------------------------------------------"
instance_package="g5"
if [ "${INSTANCE_TYPE%"${INSTANCE_TYPE#ml.g4}"}" = "ml.g4" ]; then
    instance_package="g4"
fi

echo "instance_package: $instance_package"

mkdir -p site-packages
total_start_at=$(date +%s)
start_at=$(date +%s)
# libcublas.so.11          libcudnn_cnn_infer.so.8  libnvrtc-672ee683.so.11.2
# libcublasLt.so.11        libcudnn_cnn_train.so.8  libtorch_cpu.so
# libcudnn_adv_infer.so.8  libcudnn_ops_infer.so.8  libtorch_cuda.so
# libcudnn_adv_train.so.8  libcudnn_ops_train.so.8  libtorch_cuda_linalg.so
mkdir -p site-packages/torch/lib
mv venv/lib/python3.10/site-packages/torch/lib/libcublas.so.12   site-packages/torch/lib/ 
mv venv/lib/python3.10/site-packages/torch/lib/libcublasLt.so.12   site-packages/torch/lib/ 
mv venv/lib/python3.10/site-packages/torch/lib/libcudnn_adv_infer.so.8   site-packages/torch/lib/ 
mv venv/lib/python3.10/site-packages/torch/lib/libcudnn_adv_train.so.8   site-packages/torch/lib/ 
mv venv/lib/python3.10/site-packages/torch/lib/libcudnn_cnn_infer.so.8   site-packages/torch/lib/ 
mv venv/lib/python3.10/site-packages/torch/lib/libcudnn_cnn_train.so.8   site-packages/torch/lib/ 
mv venv/lib/python3.10/site-packages/torch/lib/libcudnn_ops_infer.so.8   site-packages/torch/lib/ 
mv venv/lib/python3.10/site-packages/torch/lib/libcudnn_ops_train.so.8   site-packages/torch/lib/ 
mv venv/lib/python3.10/site-packages/torch/lib/libnvrtc-b51b459d.so.12   site-packages/torch/lib/ 
mv venv/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so   site-packages/torch/lib/ 
mv venv/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so   site-packages/torch/lib/ 
mv venv/lib/python3.10/site-packages/torch/lib/libtorch_cuda_linalg.so   site-packages/torch/lib/ 

#xformers
# _C.so _C_flashattention.so
mkdir -p site-packages/xformers/
mv venv/lib/python3.10/site-packages/xformers/_C.so site-packages/xformers/
mv venv/lib/python3.10/site-packages/xformers/_C_flashattention.so site-packages/xformers/

#llvmlite/binding/
#libllvmlite.so
mkdir -p site-packages/llvmlite/binding/
mv venv/lib/python3.10/site-packages/llvmlite/binding/libllvmlite.so site-packages/llvmlite/binding/

#triton/_C/
#libtriton.so
mkdir -p site-packages/triton/_C/
mv venv/lib/python3.10/site-packages/triton/_C/libtriton.so site-packages/triton/_C/

BUCKET_NAME="sd-ui-data-bucket-20230928"

tools/s5cmd --log=error sync site-packages/ "s3://$BUCKET_NAME/$ESD_FILE_VERSION-$instance_package/" 
tar -cf site-packages.tar venv/lib/python3.10/site-packages/
tools/s5cmd --log=error sync site-packages.tar "s3://$BUCKET_NAME/$ESD_FILE_VERSION-$instance_package/"
tar -cf repositories.tar repositories/
tools/s5cmd --log=error sync repositories.tar "s3://$BUCKET_NAME/$ESD_FILE_VERSION-$instance_package/"
end_at=$(date +%s)
cost=$((end_at-start_at))
echo "upload tar to s3://$BUCKET_NAME/$ESD_FILE_VERSION-$instance_package/*: $cost seconds"