FROM 763104351884.dkr.ecr.us-east-1.amazonaws.com/pytorch-inference:2.0.1-gpu-py310-cu118-ubuntu20.04-sagemaker

# update environment
RUN apt-get update -y

RUN mkdir /opt/ml/code && \
    git clone https://github.com/comfyanonymous/ComfyUI.git /opt/ml/code
    # git -C /opt/ml/code checkout cf1d67a6fd5ea1aa600c4df58e5b47da45f6bdbf

# download s5cmd
RUN mkdir -p /opt/ml/code/tools
RUN wget https://github.com/peak/s5cmd/releases/download/v2.0.0/s5cmd_2.0.0_Linux-64bit.tar.gz -O /opt/ml/code/tools/s5cmd_2.0.0_Linux-64bit.tar.gz
RUN tar xzvf /opt/ml/code/tools/s5cmd_2.0.0_Linux-64bit.tar.gz -C /opt/ml/code/tools/

# prepare environment fow ComfyUI
RUN pip install -r /opt/ml/code/requirements.txt && \
    pip install torch==2.0.1 torchvision==0.15.2 --extra-index-url https://download.pytorch.org/whl/cu118 && \
    pip install https://github.com/openai/CLIP/archive/d50d76daa670286dd6cacf3bcd80b5e4823fc8e1.zip && \
    pip install https://github.com/mlfoundations/open_clip/archive/bb6e834e9c70d9c27d0dc3ecedeebeaeb1ffad6b.zip && \
    pip install open-clip-torch==2.20.0

RUN apt-get install -y libtcmalloc-minimal4
ENV LD_PRELOAD /usr/lib/x86_64-linux-gnu/libtcmalloc_minimal.so.4

RUN echo "/opt/ml/code" > "/opt/conda/lib/python3.10/site-packages/packages.pth"

WORKDIR /opt/ml/code

ENV ON_DOCKER true

ENTRYPOINT ["python", "/opt/ml/code/main.py"]
