FROM 763104351884.dkr.ecr.us-east-1.amazonaws.com/pytorch-inference:2.0.1-gpu-py310-cu118-ubuntu20.04-sagemaker

# update environment
RUN apt-get update -y

RUN mkdir /home/ubuntu && \
    git clone https://github.com/comfyanonymous/ComfyUI.git /home/ubuntu/ComfyUI
    # git -C /home/ubuntu checkout cf1d67a6fd5ea1aa600c4df58e5b47da45f6bdbf

COPY comfy/serve.py /home/ubuntu/ComfyUI
COPY comfy/comfy_sagemaker_proxy.py /home/ubuntu/ComfyUI/custom_nodes

RUN pip install fastapi && \
    pip install uvicorn && \
    pip install altair

# download s5cmd
RUN mkdir -p /home/ubuntu/ComfyUI/tools
RUN wget https://github.com/peak/s5cmd/releases/download/v2.0.0/s5cmd_2.0.0_Linux-64bit.tar.gz -O /home/ubuntu/ComfyUI/tools/s5cmd_2.0.0_Linux-64bit.tar.gz
RUN tar xzvf /home/ubuntu/ComfyUI/tools/s5cmd_2.0.0_Linux-64bit.tar.gz -C /

RUN wget -q https://github.com/peak/s5cmd/releases/download/v2.2.2/s5cmd_2.2.2_Linux-64bit.tar.gz && \
    tar xzvf s5cmd_2.2.2_Linux-64bit.tar.gz && \
    rm -rf s5cmd_2.2.2_Linux-64bit.tar.gz && \
    mv s5cmd /usr/local/bin/


# prepare environment fow ComfyUI
RUN pip install -r /home/ubuntu/ComfyUI/requirements.txt && \
    pip install torch==2.0.1 torchvision==0.15.2 --extra-index-url https://download.pytorch.org/whl/cu118 && \
    pip install https://github.com/openai/CLIP/archive/d50d76daa670286dd6cacf3bcd80b5e4823fc8e1.zip && \
    pip install https://github.com/mlfoundations/open_clip/archive/bb6e834e9c70d9c27d0dc3ecedeebeaeb1ffad6b.zip && \
    pip install open-clip-torch==2.20.0

# RUN apt-get update && apt-get install -y nfs-common

# VOLUME ["/home/ubuntu/efs"]
# CMD ["sh", "-c", "mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2 fs-0662c75114e7eae65.efs.us-east-1.amazonaws.com:/ /home/ubuntu/efs"]

RUN apt-get install -y libtcmalloc-minimal4
ENV LD_PRELOAD /usr/lib/x86_64-linux-gnu/libtcmalloc_minimal.so.4

RUN echo "/home/ubuntu/ComfyUI" > "/opt/conda/lib/python3.10/site-packages/packages.pth"

WORKDIR /home/ubuntu/ComfyUI

ENV ON_DOCKER true
#ENV SAGEMAKER_PROGRAM /home/ubuntu/main.py
ENTRYPOINT ["python", "/home/ubuntu/ComfyUI/serve.py"]
