import {Aws} from "aws-cdk-lib";

export const KEY_ALIAS = 'sd-extension-password-key';
export const STACK_ID = 'Extension-for-Stable-Diffusion-on-AWS';
export const SOLUTION_NAME = 'comfy-aws-extension';
export const ESD_ROLE = `ESDRoleForEndpoint-${Aws.REGION}`;
export const ESD_POLICY_DOCUMENT = {
    Version: '2012-10-17',
    Statement: [{
        Effect: 'Allow',
        Action: [
            'sts:AssumeRole',
            'sqs:SendMessage',
            'sns:Publish',
            'sns:ListTopics',
            'sns:ListSubscriptionsByTopic',
            'kms:Encrypt',
            'kms:Decrypt',
            'iam:PassRole',
            'iam:CreateServiceLinkedRole',
            'lambda:InvokeFunction',
            'xray:PutTraceSegments',
            'xray:PutTelemetryRecords',
            's3:Get*',
            's3:List*',
            's3:PutObject',
            's3:GetObject',
            's3:HeadObject',
            's3:DeleteObject',
            'logs:PutLogEvents',
            'logs:CreateLogGroup',
            'logs:DeleteLogGroup',
            'logs:CreateLogStream',
            'dynamodb:List*',
            'dynamodb:Query',
            'dynamodb:Scan',
            'dynamodb:GetItem',
            'dynamodb:PutItem',
            'dynamodb:Describe*',
            'dynamodb:UpdateItem',
            'dynamodb:DeleteItem',
            'dynamodb:BatchGetItem',
            'dynamodb:BatchWriteItem',
            'ecr:GetRepositoryPolicy',
            'ecr:DescribeRepositories',
            'ecr:GetAuthorizationToken',
            'ecr:GetDownloadUrlForLayer',
            'ecr:BatchCheckLayerAvailability',
            'ecr:PutImage',
            'ecr:ListImages',
            'ecr:BatchGetImage',
            'ecr:DescribeImages',
            'ecr:UploadLayerPart',
            'ecr:InitiateLayerUpload',
            'ecr:CompleteLayerUpload',
            'cloudwatch:DeleteAlarms',
            'cloudwatch:PutMetricData',
            'cloudwatch:PutMetricAlarm',
            'cloudwatch:DescribeAlarms',
            'cloudwatch:DeleteDashboards',
            'sagemaker:DeleteModel',
            'sagemaker:DeleteEndpoint',
            'sagemaker:DescribeEndpoint',
            'sagemaker:DeleteEndpointConfig',
            'sagemaker:DescribeEndpointConfig',
            'sagemaker:CreateModel',
            'sagemaker:CreateEndpoint',
            'sagemaker:InvokeEndpoint',
            'sagemaker:InvokeEndpointAsync',
            'sagemaker:CreateEndpointConfig',
            'sagemaker:UpdateEndpointWeightsAndCapacities',
            'application-autoscaling:DeregisterScalableTarget',
        ],
        Resource: '*',
    }],
};
